server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/khalegjr/microservices-configs-server
#          username: username
#          password: pass
          default-label: main
          search-paths:
          - 'greeting-service*'
